//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConNguoi
    {
        public ConNguoi()
        {
            this.KhachHangs = new HashSet<KhachHang>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int IDConNguoi { get; set; }
        public string LoaiNhanSu { get; set; }
        public string GioiTinh { get; set; }
        public string Ten { get; set; }
        public string TenLot { get; set; }
        public string Ho { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Username { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string ThanhPho { get; set; }
        public string QuocGia { get; set; }
        public Nullable<int> MaPostal { get; set; }
        public string SDT { get; set; }
        public string SoThePayPal { get; set; }
        public string PasswordPayPal { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguonDB { get; set; }
    
        public virtual ServerDB ServerDB { get; set; }
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
