//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucAdmin
    {
        public string id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public int oder { get; set; }
        public string parent { get; set; }
        public string icon { get; set; }
        public int type { get; set; }
    }
}
