//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.PhanLoaiCuaSanPhams = new HashSet<PhanLoaiCuaSanPham>();
        }
    
        public int IDDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguonDB { get; set; }
    
        public virtual ServerDB ServerDB { get; set; }
        public virtual ICollection<PhanLoaiCuaSanPham> PhanLoaiCuaSanPhams { get; set; }
    }
}
