//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.ThongTinMuonSaches = new HashSet<ThongTinMuonSach>();
        }
    
        public string MaSoDocGia { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string TinhTP { get; set; }
        public string QuocGia { get; set; }
        public string KhoaLopDonVi { get; set; }
        public string Nhom { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayTheHetHan { get; set; }
        public string TrangThaiThe { get; set; }
        public string CMND { get; set; }
        public string SoMaVach { get; set; }
        public string MaSoThe { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Barcode_Of_Reader_Card Barcode_Of_Reader_Card { get; set; }
        public virtual ICollection<ThongTinMuonSach> ThongTinMuonSaches { get; set; }
    }
}
