//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.BaoCaoViPhams = new HashSet<BaoCaoViPham>();
            this.BaoCaoViPhams1 = new HashSet<BaoCaoViPham>();
            this.ChiTietPhienDauGias = new HashSet<ChiTietPhienDauGia>();
            this.DanhSachQuanTams = new HashSet<DanhSachQuanTam>();
            this.DanhSachYeuThiches = new HashSet<DanhSachYeuThich>();
            this.DanhSachYeuThiches1 = new HashSet<DanhSachYeuThich>();
            this.DonHangs = new HashSet<DonHang>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int IDKhachHang { get; set; }
        public Nullable<int> IDConNguoi { get; set; }
        public Nullable<bool> NhanMailKhuyenMai { get; set; }
        public Nullable<decimal> SoDuTaiKhoan { get; set; }
        public Nullable<double> PositiveFeedback { get; set; }
        public Nullable<int> TrangThaiHoatDong { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguonDB { get; set; }
    
        public virtual ICollection<BaoCaoViPham> BaoCaoViPhams { get; set; }
        public virtual ICollection<BaoCaoViPham> BaoCaoViPhams1 { get; set; }
        public virtual ICollection<ChiTietPhienDauGia> ChiTietPhienDauGias { get; set; }
        public virtual ConNguoi ConNguoi { get; set; }
        public virtual ICollection<DanhSachQuanTam> DanhSachQuanTams { get; set; }
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches { get; set; }
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches1 { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ServerDB ServerDB { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
