//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.BaoCaoViPhams = new HashSet<BaoCaoViPham>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int IDNhanVien { get; set; }
        public Nullable<int> IDConNguoi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<int> BacLuong { get; set; }
        public Nullable<int> SoGioDaNghiPhep { get; set; }
        public Nullable<bool> TinhTrangHoatDong { get; set; }
        public string TenCongViec { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguonDB { get; set; }
    
        public virtual ICollection<BaoCaoViPham> BaoCaoViPhams { get; set; }
        public virtual ConNguoi ConNguoi { get; set; }
        public virtual ServerDB ServerDB { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
