//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.ThongTinMuonSaches = new HashSet<ThongTinMuonSach>();
        }
    
        public int SoDangKyCaBiet { get; set; }
        public string NhanDe { get; set; }
        public string NhaXuatBan { get; set; }
        public string TacGia { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual ICollection<ThongTinMuonSach> ThongTinMuonSaches { get; set; }
    }
}
