//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BaoCaoViPhams = new HashSet<BaoCaoViPham>();
            this.ChiTietPhienDauGias = new HashSet<ChiTietPhienDauGia>();
            this.DanhSachQuanTams = new HashSet<DanhSachQuanTam>();
            this.DanhSachYeuThiches = new HashSet<DanhSachYeuThich>();
            this.DonHangs = new HashSet<DonHang>();
            this.HinhAnhSanPhams = new HashSet<HinhAnhSanPham>();
            this.MoTaSanPhams = new HashSet<MoTaSanPham>();
            this.PhanLoaiCuaSanPhams = new HashSet<PhanLoaiCuaSanPham>();
        }
    
        public int IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string KichCo { get; set; }
        public Nullable<decimal> GiaKhoiDiem { get; set; }
        public Nullable<decimal> GiaMuaNgay { get; set; }
        public string DiaDiemChapNhanGiaoHang { get; set; }
        public Nullable<int> ThoiGianHoanThanhGiaoHang { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string ThuongHieu { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DiaChiHienTaiCuaSanPham { get; set; }
        public Nullable<decimal> MucTangGia { get; set; }
        public Nullable<int> MaNguoiBan { get; set; }
        public Nullable<int> MaNhanVienKiemDinh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguonDB { get; set; }
    
        public virtual ICollection<BaoCaoViPham> BaoCaoViPhams { get; set; }
        public virtual ICollection<ChiTietPhienDauGia> ChiTietPhienDauGias { get; set; }
        public virtual ICollection<DanhSachQuanTam> DanhSachQuanTams { get; set; }
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<MoTaSanPham> MoTaSanPhams { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<PhanLoaiCuaSanPham> PhanLoaiCuaSanPhams { get; set; }
        public virtual ServerDB ServerDB { get; set; }
    }
}
