//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerDB
    {
        public ServerDB()
        {
            this.BaoCaoViPhams = new HashSet<BaoCaoViPham>();
            this.ChiTietPhienDauGias = new HashSet<ChiTietPhienDauGia>();
            this.ConNguois = new HashSet<ConNguoi>();
            this.DanhMucs = new HashSet<DanhMuc>();
            this.DanhSachQuanTams = new HashSet<DanhSachQuanTam>();
            this.DanhSachYeuThiches = new HashSet<DanhSachYeuThich>();
            this.DonHangs = new HashSet<DonHang>();
            this.HinhAnhSanPhams = new HashSet<HinhAnhSanPham>();
            this.KhachHangs = new HashSet<KhachHang>();
            this.MoTaSanPhams = new HashSet<MoTaSanPham>();
            this.NhanViens = new HashSet<NhanVien>();
            this.PhanLoaiCuaSanPhams = new HashSet<PhanLoaiCuaSanPham>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int IDServer { get; set; }
        public string TenServer { get; set; }
    
        public virtual ICollection<BaoCaoViPham> BaoCaoViPhams { get; set; }
        public virtual ICollection<ChiTietPhienDauGia> ChiTietPhienDauGias { get; set; }
        public virtual ICollection<ConNguoi> ConNguois { get; set; }
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        public virtual ICollection<DanhSachQuanTam> DanhSachQuanTams { get; set; }
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual ICollection<MoTaSanPham> MoTaSanPhams { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        public virtual ICollection<PhanLoaiCuaSanPham> PhanLoaiCuaSanPhams { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
