//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuVienEntities3 : DbContext
    {
        public QuanLyThuVienEntities3()
            : base("name=QuanLyThuVienEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Barcode_Of_Reader_Card> Barcode_Of_Reader_Card { get; set; }
        public DbSet<DocGia> DocGias { get; set; }
        public DbSet<Sach> Saches { get; set; }
        public DbSet<ThongTinMuonSach> ThongTinMuonSaches { get; set; }
        public DbSet<YKienDocGia> YKienDocGias { get; set; }
    }
}
